import { create } from "zustand";

export const useAnalyticsStore = create((set) => ({
  dayPoints: [],
  dayLabels: [],
  dayPosts: [],
  subscriberPoints: [],
  subscriberLabels: [],
  subscriberDayPoints: [],
  subscriberDayLabels: [],
  adReachPoints: [],
  adReachLabels: [],
  postsByPeriodPoints: [],
  postsByPeriodLabels: [],
  postsByPeriodHourly: [],
  averageCoverageAvgPoints: [],
  averageCoverageAvgLabels: [],

  averageCoverageErPoints: [],
  averageCoverageErLabels: [],

  averageCoverageErr24Points: [],
  averageCoverageErr24Labels: [],

  averageCoverageErrPoints: [],
  averageCoverageErrLabels: [],

  dayFilter: "24h",
  subscriberFilter: "24h",
  adReachFilter: "24h",
  postsByPeriodFilter: "24h",
  averageCoverageAvgFilter: "24h",
  averageCoverageErFilter: "week",
  averageCoverageErr24Filter: "week",
  averageCoverageErrFilter: "week",

  setDayData: (points, labels, posts) => set({ dayPoints: points, dayLabels: labels, dayPosts: posts }),
  setSubscriberData: (points, labels) => set({ subscriberPoints: points, subscriberLabels: labels }),
  setSubscriberDayData: (points, labels) => set({ subscriberDayPoints: points, subscriberDayLabels: labels }),
  setAdReachData: (points, labels) => set({ adReachPoints: points, adReachLabels: labels }),
  setPostsByPeriodData: (points, labels, hourly) => set({ postsByPeriodPoints: points, postsByPeriodLabels: labels, postsByPeriodHourly: hourly }),
  setAverageCoverageAvgData: (points, labels) => set({ averageCoverageAvgPoints: points, averageCoverageAvgLabels: labels }),
  setAverageCoverageErData: (points, labels) => set({ averageCoverageErPoints: points, averageCoverageErLabels: labels }),
  setAverageCoverageErr24Data: (points, labels) => set({ averageCoverageErr24Points: points, averageCoverageErr24Labels: labels }),
  setAverageCoverageErrData: (points, labels) => set({ averageCoverageErrPoints: points, averageCoverageErrLabels: labels }),

  setDayFilter: (filter) => set({ dayFilter: filter }),
  setSubscriberFilter: (filter) => set({ subscriberFilter: filter }),
  setAdReachFilter: (filter) => set({ adReachFilter: filter }),
  setPostsByPeriodFilter: (filter) => set({ postsByPeriodFilter: filter }),
  setAverageCoverageAvgFilter: (filter) => set({ averageCoverageAvgFilter: filter }),
  setAverageCoverageErFilter: (filter) => set({ averageCoverageErFilter: filter }),
  setAverageCoverageErr24Filter: (filter) => set({ averageCoverageErr24Filter: filter }),
  setAverageCoverageErrFilter: (filter) => set({ averageCoverageErrFilter: filter }),
}));
